apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - |
          echo 'Greenwell Site - Health Check';
          apt-get -qq update > /dev/null; apt-get -qq -y install curl > /dev/null;
          alive=$(curl https://greenwell-app.eu-de.mybluemix.net/health);
          if [ "$alive" == "200 - Healthy" ];
          then echo "TEST PASS - 200"; exit 0;
          else echo "TEST FAIL - $alive"; exit 1;
          fi
          a=200
          b=10
          c=4
          echo $(seq 6)
          echo $(seq $c)
          for i in $(seq $a)
          do
            echo "Welcome for the ${i}-th time out of $a"
          done
          for i in $(seq $b)
          do
            echo "Sleeping $c seconds for the ${i}-th time out of $b"
            sleep $c
          done
    - name: task-two
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo "SHAZBOT2"      
